// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApiCSVParser.Models;

#nullable disable

namespace webapicsvparser.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250805185249_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApiCSVParser.Models.Result", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AvgExecutionTime")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_exect_time");

                    b.Property<double>("AvgValue")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_value");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<double>("MaxValue")
                        .HasColumnType("double precision")
                        .HasColumnName("max_value");

                    b.Property<double>("MedianValue")
                        .HasColumnType("double precision")
                        .HasColumnName("median_value");

                    b.Property<DateTime>("MinDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("min_date");

                    b.Property<double>("MinValue")
                        .HasColumnType("double precision")
                        .HasColumnName("min_value");

                    b.Property<int>("SecDeltaDate")
                        .HasColumnType("integer")
                        .HasColumnName("sec_delta_date");

                    b.HasKey("Id");

                    b.HasIndex("FileName")
                        .IsUnique();

                    b.ToTable("results");
                });

            modelBuilder.Entity("WebApiCSVParser.Models.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<double>("ExecutionTime")
                        .HasColumnType("double precision")
                        .HasColumnName("execution_time");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<double>("Value_")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("values");
                });
#pragma warning restore 612, 618
        }
    }
}
